import type { Product } from "../types/product";

export const ALL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Grafik Baskılı T-Shirt",
    value: 120,
    category: "Erkek",
    brand: "VERSACE",
    oldValue: 180,
    image: "/Frame-10.png",
    rating: 4.5,
    color: "brand-khaki",
    size: ["S", "L", "XL"],
  },
  {
    id: 2,
    name: "Skinny Fit Denim Jean",
    value: 240,
    category: "Erkek",
    brand: "CALVIN KLEIN",
    image: "/Frame-33.png",
    rating: 3.5,
    color: "brand-denim",
    size: ["M", "L", "XL"],
  },
  {
    id: 3,
    name: "Klasik Kareli Gömlek",
    value: 180,
    category: "Kadın",
    brand: "ZARA",
    image: "/Frame-34.png",
    rating: 4.5,
    color: "brand-denim",
    size: ["S", "M", "XL"],
  },
  {
    id: 4,
    name: "Çizgili Çocuk T-Shirt",
    value: 130,
    category: "Çocuk",
    brand: "GUCCI",
    image: "/Frame-12.png",
    rating: 4.2,
    color: "brand-khaki",
    size: ["S", "M", "L", "XL"],
  },
  {
    id: 5,
    name: "Dikey Çizgili Premium Gömlek",
    value: 212,
    category: "Erkek",
    brand: "PRADA",
    image: "/Frame-36.png",
    rating: 5.0,
    color: "brand-green",
  },
  {
    id: 6,
    name: "Modern Kesim Basic T-Shirt",
    value: 145,
    category: "Kadın",
    brand: "ZARA",
    oldValue: 220,
    image: "/Frame-32.png",
    rating: 4.0,
    color: "brand-khaki",
    size: ["S", "M", "L", "XL"],
  },
  {
    id: 7,
    name: "Bermuda Chino Şort",
    value: 80,
    category: "Çocuk",
    brand: "GUCCI",
    oldValue: 120,
    image: "/Frame-38.png",
    rating: 4.0,
    color: "brand-denim",
    size: ["S", "M", "L", "XL"],
  },
  {
    id: 8,
    name: "Denim Çocuk Pantolonu",
    value: 210,
    category: "Çocuk",
    brand: "CALVIN KLEIN",
    image: "/Frame-39.png",
    rating: 4.7,
    color: "brand-denim",
    size: ["S", "M", "L", "XL"],
  },
  {
    id: 10,
    name: "One Life Graphic T-shirt",
    value: 180,
    category: "Erkek",
    brand: "PRADA",
    image: "/Frame-13.png",
    rating: 4.5,
    color: "brand-denim",
    size: ["S", "M", "L", "XL"],
  },
  {
    id: 11,
    name: "Çizgili Kol Detaylı T-Shirt",
    value: 130,
    category: "Kadın",
    brand: "VERSACE",
    oldValue: 320,
    image: "/Frame-35.png",
    rating: 4.3,
    color: "brand-denim",
    size: ["S", "M", "L", "XL"],
  },
  {
    id: 12,
    name: "Vertical Striped Premium Shirt",
    value: 212,
    category: "Erkek",
    brand: "GUCCI",
    oldValue: 320,
    image: "/Frame-11.png",
    rating: 5.0,
    color: "brand-denim",
    size: ["S", "M", "L"],
  },
  {
    id: 13,
    name: "Courage Grafik Baskılı T-Shirt",
    value: 145,
    category: "Çocuk",
    brand: "ZARA",
    oldValue: 220,
    image: "/Frame-37.png",
    rating: 4.0,
    color: "brand-green",
  },
];
